// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBytEAiwzT8ToLxNVXlO5XzJHrcrDqF4I',
    appId: '1:641572541062:web:db0beecde3907c955eb707',
    messagingSenderId: '641572541062',
    projectId: 'watch-vault-926e2',
    authDomain: 'watch-vault-926e2.firebaseapp.com',
    storageBucket: 'watch-vault-926e2.appspot.com',
    measurementId: 'G-QL4BHF059Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERH4EFLmLFDX7Q-VJmeQ79HspjoKISy8',
    appId: '1:641572541062:android:677a5e88ac922a645eb707',
    messagingSenderId: '641572541062',
    projectId: 'watch-vault-926e2',
    storageBucket: 'watch-vault-926e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGotZ06MWUmdqEbr2O7Bx7LQVRrjLDXcM',
    appId: '1:641572541062:ios:2e16c318b247d9a95eb707',
    messagingSenderId: '641572541062',
    projectId: 'watch-vault-926e2',
    storageBucket: 'watch-vault-926e2.appspot.com',
    iosClientId: '641572541062-3nmkt87olm87kibc171trmakgf17dto3.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGotZ06MWUmdqEbr2O7Bx7LQVRrjLDXcM',
    appId: '1:641572541062:ios:2e16c318b247d9a95eb707',
    messagingSenderId: '641572541062',
    projectId: 'watch-vault-926e2',
    storageBucket: 'watch-vault-926e2.appspot.com',
    iosClientId: '641572541062-3nmkt87olm87kibc171trmakgf17dto3.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchVault',
  );
}
